<!DOCTYPE html>
<html>

<head>
    <title>
        PHP Tag
    </title>
</head>

<body>
    <p> This is plain HTML </p>
    <?php
    // This is a comment
    echo "This is a text generated by PHP";
    ?>
    <p>This is again HTML</P>
    <?php
    /*
  This is a comment
  that goes over many lines.
*/
    echo "This is again a php text";
    ?>

</body>

</html>